### ISSUE TITLE
增加“微信支持”文档

### ISSUE THREAD

**Issue by ruizeng** [PandoCloud/tisan-doc#9]
文档中说明如何通过关注freeiot公众号对硬件进行测试

**Comment by sw0813** [comment]
已经增加，但未展开说明

**Comment by ruizeng** [comment]
微信的使用流程整体如下，
@sw0813 抽时间整体细化下：
1. 关注freeiot微信公众账号
2. 使用wifi配置对开发板进行联网配置
3. 点击web ide手机下面的二维码按钮，点击公众号菜单中的扫描设备扫描二维码
4. 如果添加成功，便可以在我的设备菜单找到设备，进行控制测试
